config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :categories, only: %i[new create destroy] do
    resources :entities, only: %i[index new create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Category, user_id: user.id
    can :read, Entity, user_id: user.id
    can :destroy, Category, user_id: user.id
    can :destroy, Entity, user_id: user.id
    can :manage, Category, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_entity.rb
class CategoriesEntity < ApplicationRecord
  belongs_to :category
  belongs_to :entity
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  has_many :categories_entities, dependent: :destroy
  has_many :entities, through: :categories_entities, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user

  has_many :categories_entities, dependent: :destroy
  has_many :categories, through: :categories_entities, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :categories_transfers, dependent: :destroy
  has_many :categories, through: :categories_transfers, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_one_attached :avatar
  has_many :entities
  has_many :categories

  # def avatar_thumbnail
  #   if avatar.attached?
  #     avatar.variant(resize: "150x150!").processed
  #   else
  #     '/default_profile.jpg'
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Devise::Controllers::Helpers
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(name: category_params[:name], icon: category_params[:icon], user_id: current_user.id)

    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @entities = @category.entities
    @categories = current_user.categories.all
  end

  def new
    @entity = Entity.new
    @group = Category.new
    @categories = current_user.categories.all
  end

  def create
    @entity = Entity.new(name: entity_params[:name], amount: entity_params[:amount], user_id: current_user.id)
    if @entity.save
      @categories_entites = CategoriesEntity.new(category_id: params[:category_id], entity_id: @entity.id)
      if @categories_entites.save
        redirect_to category_entities_path, notice: 'Entity was successfully created.'
      else
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @entity = @category.entities.find(params[:id])
    @entity.destroy
    redirect_to category_entities_path(@category)
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!

  def home
    return unless current_user.present?

    @categories = Category.where(user_id: current_user.id).order(created_at: :desc) || []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/new.html.erb
<%= render '/shared/user_navbar'%>
<main class="container mx-auto px-5 mt-5  w-full">
  <%= form_with(model: @category, url: categories_path, method: :post) do |f|%>
    <div class= 'grid grid-col gap-3 w-full'>
      <div class="field  w-full ">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name', class: 'border-b border-b-[#d1d1d1] p-3 focus:outline-none w-full' %>
      </div>
      <div class="field  w-full">
        <%= f.text_field :icon, autofocus: true, autocomplete: "name", placeholder: 'Add your icon url here', class: 'border-b border-b-[#d1d1d1] p-3 focus:outline-none w-full' %>
      </div>
      <%= f.submit "Add Category",class:"btn btn-primary" %>
    </div>
  <%end%>
</main>

app/views/entities/index.html.erb
<div class="flex flex-col justify-between h-screen">
  <div>
    <div>
    <%= render '/shared/user_navbar'%>
    <div class="flex justify-between w-full shadow px-5 py-3">
      <p>Credit</p>
      <small>
        <% credit = 0 %> <% @categories.each do |category| %> <%
        category.entities.each do |transaction| %> <% credit +=
        transaction.amount %> <% end %> <% end %> <%= "$#{credit}" %>
      </small>
    </div>
    <main class="container mx-auto px-5 mt-5 w-full">
      <% if @entities.empty? %>
      <h1 class="text-center p-3 bg-red-500 text-white shadow-xl">
        No Transanction
      </h1>
      <%else%> <%@entities.each do |entity|%>
      <div class="flex justify-between shadow-xl p-4">
        <div class="grid content-between">
          <p class=""><%= entity.name %></p>
          <span class="text-sm"
            ><%= entity.created_at.strftime("%b %d, %Y") %></span
          >
        </div>
        <div class="grid content-between">
          <p class="font-bold text-xl"><%= entity.amount %></p>
          <% if can? :destroy, entity %> <%= button_to category_entity_path(
          @category.id, entity.id), method: :delete do %>

          <span class="text-sm hover:text-red-600">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="25"
              height="30"
              viewBox="0 0 48 48"
            >
              <path
                fill="currentColor"
                d="M20 10.5v.5h8v-.5a4 4 0 0 0-8 0Zm-2.5.5v-.5a6.5 6.5 0 1 1 13 0v.5h11.25a1.25 1.25 0 1 1 0 2.5h-2.917l-2 23.856A7.25 7.25 0 0 1 29.608 44H18.392a7.25 7.25 0 0 1-7.224-6.644l-2-23.856H6.25a1.25 1.25 0 1 1 0-2.5H17.5Zm4 9.25a1.25 1.25 0 1 0-2.5 0v14.5a1.25 1.25 0 1 0 2.5 0v-14.5ZM27.75 19c-.69 0-1.25.56-1.25 1.25v14.5a1.25 1.25 0 1 0 2.5 0v-14.5c0-.69-.56-1.25-1.25-1.25Z"
              />
            </svg>
          </span>
          <% end %> <% end %>
        </div>
      </div>
      <%end%> <%end%>
    </main>
  </div>
  </div>
  <div class="flex text-center justify-center bg-[#5FB523] p-3">
    <%= link_to 'ADD TRANSANCTION', new_category_entity_path, class:"border
    border-xl border-white text-white px-8"%>
  </div>
</div>

app/views/entities/new.html.erb
<%= render '/shared/user_navbar' %>
<main class="container mx-auto px-5 mt-5  w-full">
    <%= form_with(model: @entity, url: category_entities_path(params[:category_id]) , method: :post) do |f|%>
      <div class= 'grid grid-col gap-3 w-full'>
        <div class="field  w-full ">
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Name', class: 'border-b border-b-[#d1d1d1] p-3 focus:outline-none w-full' %>
        </div>
        <div class="field  w-full">
          <%= f.text_field :amount, autofocus: true, autocomplete: "name", placeholder: 'Amount', class: 'border-b border-b-[#d1d1d1] p-3 focus:outline-none w-full' %>
        </div>
        <div class="form-group mb-3">
          <%= select_tag "group", options_for_select(@categories.map { |group| [group.name, group.id] }), {prompt:"Select Category", required:true, class:"form-select"}%>
        </div>
        <%= f.submit "Add Transanction",class:"btn btn-primary" %>
      </div>
    <%end%>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/daisyui@2.14.1/dist/full.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <% if current_user && current_user.present?  %>
  <%= render '/shared/categories' %>
  <% else %>
    <%= render '/shared/home'%>
  <% end %>

app/views/shared/_categories.html.erb
<div class="grid content-between h-screen">
  <div>
<div class="navbar text-white bg-[#3378C2]">
  <div class="navbar-start">
    <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z" />
          </g>
        </g>
      </svg>
    <% end %>
  </div>
  <div class="navbar-center">CATEGORIES</div>
  <div class="navbar-end">
    <%= button_to destroy_user_session_path, method: :delete do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g fill="currentColor">
          <path d="M12 3.25a.75.75 0 0 1 0 1.5a7.25 7.25 0 0 0 0 14.5a.75.75 0 0 1 0 1.5a8.75 8.75 0 1 1 0-17.5Z" />
          <path d="M16.47 9.53a.75.75 0 0 1 1.06-1.06l3 3a.75.75 0 0 1 0 1.06l-3 3a.75.75 0 1 1-1.06-1.06l1.72-1.72H10a.75.75 0 0 1 0-1.5h8.19l-1.72-1.72Z" />
        </g>
      </svg>
    <% end %>
  </div>
</div>

<div class="flex justify-between w-full shadow text-xl px-5 py-3">
  <p>Credit</p>
  <small class="font-bold text-xl">
    <% credit = 0 %>
    <% @categories.each do |category| %>
      <% category.entities.each do |transaction| %>
        <% credit += transaction.amount %>
      <% end %>
    <% end %>
    <%= "$#{credit}" %>
  </small>
</div>
  <div>
      <main class="container mx-auto px-5 mt-5 w-full">
        <% if @categories.empty? %>
            <div class="flex -w-full">
              <h class="text-xl text-center bg-red-500 text-white p-3 w-full">No categories</h>
            </div>
        <% else %>
          <% @categories.each do |category| %>
            <div class="flex justify-between shadow-xl p-4 w-full">
              <div class="flex gap-3 w-full">
              <div class="avatar">
                <%= link_to category_entities_path(category.id) do %>
                  <div class="w-24 mask mask-squircle">
                    <img src="<%= category.icon %>" />
                  </div>
                <% end %>
              </div>
              <div class="grid content-between">
                <p class="text-xl">
                  <%= link_to category_entities_path(category.id) do %>
                    <%= category.name %>
                  <% end %>
                </p>
                <span class="text-sm">
                  <%= category.created_at.strftime("%b %d, %Y") %>
                </span>
              </div>
              </div>
              <div class="flex flex-col justify-between">
                <p class="font-bold text-xl">
                  <% sum = 0 %>
                  <% category.entities.each do |transaction| %>
                    <% sum += transaction.amount %>
                  <% end %>
                  <%= "$#{sum}" %>
                </p>
                <% if can? :destroy, category %>
                  <%= button_to category_path(category.id), method: :delete, title: "Delete #{category.name.capitalize} category" do %>
                    <span class="text-sm hover:text-red-600">
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="30" viewBox="0 0 48 48">
                        <path fill="currentColor" d="M20 10.5v.5h8v-.5a4 4 0 0 0-8 0Zm-2.5.5v-.5a6.5 6.5 0 1 1 13 0v.5h11.25a1.25 1.25 0 1 1 0 2.5h-2.917l-2 23.856A7.25 7.25 0 0 1 29.608 44H18.392a7.25 7.25 0 0 1-7.224-6.644l-2-23.856H6.25a1.25 1.25 0 1 1 0-2.5H17.5Zm4 9.25a1.25 1.25 0 1 0-2.5 0v14.5a1.25 1.25 0 1 0 2.5 0v-14.5ZM27.75 19c-.69 0-1.25.56-1.25 1.25v14.5a1.25 1.25 0 1 0 2.5 0v-14.5c0-.69-.56-1.25-1.25-1.25Z" />
                      </svg>
                    </span>
                  <% end %>
                <% end %>
      
              </div>
            </div>
          <% end %>
        <% end %>
      </main>
  </div>
</div>
<div class="flex flex-col text-center justify-end bg-[#5FB523] p-3">
  <%= link_to 'Add Categories', new_category_path, class: "border border-xl border-white text-white px-8" %>
</div>
</div>

app/views/shared/_home.html.erb
<div class="grid grid-col h-screen w-full items-center ">
  <div class="w-full">
    <h1 class="text-3xl text-center italic">Budget APP</h1>
  </div>
  <div class="flex flex-col justify-end h-full flex-end w-full flex-end ">
    <%= link_to "LOG IN", new_user_session_path, class: 'bg-[#3778C2] text-center p-3 text-white w-full' %>
    <%= link_to  "SIGN UP", new_user_registration_path, class: ' p-3 w-full text-center' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if devise_mapping.registerable? && controller_name == 'registrations' && action_name == 'new' %>

  <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      REGISTER
    </div>
    <div class="navbar-end"> 
      <%= link_to "Log in", new_user_session_path %>
    </div>
  </div>

<% elsif devise_mapping.recoverable? && controller_name == 'sessions' && action_name == 'new' %>

  <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      LOGIN
    </div>
    <div class="navbar-end"> 
      <%= link_to  "Sign up", new_user_registration_path %>
    </div>
  </div>

<% end %>

app/views/shared/_user_navbar.html.erb
<% if devise_mapping = Devise.mappings[:user] && controller_name == 'categories' && action_name == 'new' %>
  <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      ADD CATEGORY
    </div>
    <div class="navbar-end"> 
      <%= link_to  "Next", new_user_registration_path %>
    </div>
  </div>

<% elsif devise_mapping = Devise.mappings[:user] && controller_name == 'entities' && action_name == 'new'%>
   <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      TRANSANCTION
    </div>
    <div class="navbar-end"> 
      <%= link_to  "Next", new_user_registration_path %>
    </div>
  </div>

  
<% elsif devise_mapping = Devise.mappings[:user] && controller_name == 'entities' && action_name == 'index'%>
   <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      TRANSANCTION
    </div>
    <div class="navbar-end"> 
      <%= link_to  "Next" %>
    </div>
  </div>

  <% elsif devise_mapping = Devise.mappings[:user] && controller_name == 'home' && action_name == 'home'%>
   <div class="navbar text-white bg-[#3378C2]">
    <div class="navbar-start">
      <%= link_to(root_path, class: "btn btn-ghost normal-case text-xl") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <g id="evaArrowIosBackFill0">
          <g id="evaArrowIosBackFill1">
            <path id="evaArrowIosBackFill2" fill="currentColor" d="M13.83 19a1 1 0 0 1-.78-.37l-4.83-6a1 1 0 0 1 0-1.27l5-6a1 1 0 0 1 1.54 1.28L10.29 12l4.32 5.36a1 1 0 0 1-.78 1.64Z"/>
          </g>
        </g>
      </svg>
    <% end %>
    </div>
    <div class="navbar-center">
      TRANSANCTION
    </div>
    <div class="navbar-end"> 
      <%= link_to  "Next" %>
    </div>
  </div>
<%end%>